### ISSUE TITLE
Map Code Fetch API Error?

### ISSUE THREAD

**Issue by oliviacarl** [DATA300L111-20S/Project-Zero-TCL#1]
When copying over the Brazil Map.html code to our main html file (this one), it doesn't run, giving us the error "Fetch API cannot load." There is an svg made, however the path and map code itself is not in it. We aren't sure what is causing this issue.

**Comment by Tientuine** [comment]
@oliviacarl Can you explain to me how I can reproduce this problem on my computer? I have pulled the latest version of your repository, but I'm not sure which file to view.

**Comment by Tientuine** [comment]
P.S. I think that you are missing files from your repository. I tried loading TCL.html, assuming that file is likely the main HTML file that you were referring to, but it cannot find the d3.js file since that file is not included in your repository.

**Comment by oliviacarl** [comment]
I added the d3.js file to the repository. And, it is the TCL.html file that has the issue. The Brazil Map.html files runs fine and produces the map, but when I added that code to our main .html file the map does not show up.

**Comment by Tientuine** [comment]
You say "when I added that code to our main file"... Is that reflected in the version on GitHub? If not, can you commit and push the broken code that you are talking about so that I can run the exact same thing you are?

**Comment by oliviacarl** [comment]
It should be, but I commited it again to be sure. When I say added, I copied the code and put in into the TCL.html file, but the map does not appear.

**Comment by Tientuine** [comment]
I've added some comments to commit 6e3424735493940ed9f404bce13dd35d2189620e where you first added the map code into the main file.

**Comment by oliviacarl** [comment]
I made the changes you suggested and tried to debug the rest of it, but I'm still running into the same issue. Does the d3 source have to be changed to v5?

**Comment by Tientuine** [comment]
The `d3.js` file in your repository **is** version 5. The change in syntax to use Promises must be made anywhere that you load data. This means that you should make the same change when loading your JSON file. I probably should have mentioned that in my other comments.

**Comment by oliviacarl** [comment]
I changed the syntax to use Promises, but it still isn't loading and it shows no errors.

**Comment by Tientuine** [comment]
It's strange that you don't see any errors, because when I pull the latest from your repository and run it, both Firefox and Chrome show errors.

From Chrome:
```
d3.js:1197 Error: <svg> attribute height: Expected length, "NaN".
(anonymous) @ d3.js:1197
TCL.html:112 Uncaught (in promise) TypeError: data.forEach is not a function
    at TCL.html:112
    at d3.js:5907
    at d3.js:5957
    at parseRows (d3.js:6006)
    at parse (d3.js:5956)
    at d3.js:6129
```

From Firefox:
```
Unexpected value NaN parsing height attribute. d3.js:1197:9
TypeError: data.forEach is not a function TCL.html:112:14
```

And when I look at the code on line 112, I can see that it is not using the Promise, but rather the older v4 style. Did you push your latest code?

**Comment by oliviacarl** [comment]
Yes, we do get those errors, but for the bar chart and the line chart. How do we change that to be in the Promise format? I changed the map code to the Promise format, but thats not showing up so I thought something must be broken with that code, regardless of the errors from the bar chart.

**Comment by Tientuine** [comment]
Understood. So, the problem with your map lies in how you are handling the Promises. I'll add comments on your latest commit with a suggestion for how to fix.
