### ISSUE TITLE
Fetch API PART TWO

### ISSUE THREAD

**Issue by angelijp** [DATA300L111-20S/Project-Zero-TCL#3]
With the line chart, I have most of it up and running, however, it's giving the same error. I know Olivia's was a bit different, however, all I am trying to do is switch formatting to d3.V5. The console reads the Fetched API cannot load with my csv url attached along with Uncaught in promise. Some suggestions for the error said to run a python server so I've tried running it but that didn't do much of anything. I'm not so sure how promises will work in this code and would like some further clarification if possible!

**Comment by Tientuine** [comment]
Check out the recent video I posted about running a local Web server with Node.js, it might help.

**Comment by angelijp** [comment]
I made two promises for line chart and bar chart in TCL.html, however they still don't show up and I'm unsure if I did them properly unless they are missing something?
