### ISSUE TITLE
Bar Chart Sizing - TCL.html

### ISSUE THREAD

**Issue by angelijp** [DATA300L111-20S/Project-Zero-TCL#4]
I followed on what your suggestions were yesterday when appending the SVG. I got both the line and the bar chart to fully show up however, the bar chart is giving me issues with sizing. It doesn't let me add width and height as I'd like without it chopping off the x-axis but when I change the sizing of the line chart, I works fine except not showing one the axes.

**Comment by Tientuine** [comment]
I might find some time later tonight to look deeper, but in the meantime I would like to suggest that you switch from using the width and height attributes to use viewBox instead. It is a better method and allows your SVG to resize flexibly with the available space. In conjunction with that, however, you will have to set the **width** of the SVG in your CSS style rules to something percentage-based, like 100% or 80% (whatever looks good to you).
